# Generated by Django 4.0.2 on 2022-02-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Lunes'), ('Tuesday', 'Martes'), ('Wednesday', 'Miércoles'), ('Thursday', 'Jueves'), ('Friday', 'Viernes')], default=None, max_length=20)),
                ('hour', models.CharField(choices=[('9', '9.00'), ('10', '10.00'), ('11', '11.00'), ('12', '12.00'), ('13', '13.00'), ('14', '14.00'), ('15', '15.00'), ('16', '16.00'), ('17', '17.00'), ('18', '18.00'), ('19', '19.00')], default=None, max_length=20)),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'db_table': 'Schedules',
                'ordering': ['day', '-hour'],
            },
        ),
    ]
