# Generated by Django 4.0.2 on 2022-02-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200, verbose_name='Email')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=220, verbose_name='Apellido')),
                ('disponibility', models.ManyToManyField(to='schedule.Schedule')),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
                'db_table': 'teachers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200, verbose_name='Email')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=220, verbose_name='Apellido')),
                ('modality', models.CharField(choices=[('individual', 'Individual'), ('grupal', 'Grupal')], default='Grupal', max_length=20)),
                ('level', models.CharField(choices=[('begginer', 'Begginer'), ('pre_intermediate', 'Pre_Intermediate'), ('intermediate', 'Intermediate'), ('upper_intermediate', 'Upper-intermediate'), ('advanced', 'Advanced')], default='Begginer', max_length=20)),
                ('disponibility', models.ManyToManyField(to='schedule.Schedule')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'db_table': 'students',
                'ordering': ['name'],
            },
        ),
    ]
